import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      phone: '0926073422',
      password: bcrypt.hashSync ('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      phone:  '0905321351',
      password: bcrypt.hashSync ('123456'),
      isAdmin: false,
    },
    {
      name: 'Derek',
      email: 'derekcao0522@hotmail.com',
      phone:  '0935715719',
      password: bcrypt.hashSync ('1111'),
      isAdmin: true,
    },
  ],
  products: [
      {
        // _id: "1",
        name: "Arya Stark",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEWTUTnhpfbohKWODYMnn0eSHVh-noJkQuRznf_rKeuwu_OBn36hosu6Is85zqFLm6O1kaUUpGdzh0prOzEym612GcK2833K28dfTqMmTO6T1DtAnPzEXShVfJZLM5ncJdYhQ2s6_k_PqTwkgytBwSxb=w679-h829-no?authuser=0",
        calorie: 864,
        category: "burgers", 
        price: 100,
        slug: "arya-stark",
        notice: "Pork",
        ingredients: "Pork, mushrooms, Swiss cheese, lettuce, tomato, red onion, pickle, ketchup and our Famous sauce.",
        countInStock: 1,
      },
      {
        // _id: "2",
        name: "Tyrion Lannister",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEVwouD_qZNFYuZeg4L2MztevWM-x0NDa2GxXjyhxduRlCi5SoI4eHMi2K2t-f9CYqPL0e7GgUGfigcDn3ZLaxva8UtZ-2F3A1Xs9KJWPFymHnF3ZQI9oEWQcgxKomic7vbdcdliO7MjZhOqaw_KdSaP=w679-h829-no?authuser=0",
        calorie: 864, 
        category: "burgers",
        price: 110,
        slug: "tyrion-lannister",
        notice: "",
        ingredients: "ANGUS BEEF, California Avocado, salsa, American cheese, lettuce, tomato, red onion, pickle, ketchup and our Famous sauce.",
        countInStock: 17,
      },
      {
        // _id: "3",  
        name: "Daenerys Targaryen",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEVJn35SMhC9au5vJ8ec_pSUBfjrcV8VtL6-6psKOjobCbB_UwLViOylJfLUdJSNSG_v5jUFNrQIvRWe9iiM5_c-_-5x-ywat_B6T_Mz1q4YAv_me496IWVl7rui9Np1RIGGBE7cUXNecvHBBvG7Eeme=w679-h829-no?authuser=0",
        calorie: 864, 
        category: "burgers",
        price: 120,
        slug: "daenerys-targaryen",
        notice:  "Spicy",
        ingredients: "Jalapeno, sriracha sauce, beef bacon, Swiss cheese, lettuce, tomato and our Famous sauce.",
        countInStock: 10,
      },
      {
        // _id: "4",
        name: "Brienne of Tarth",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEVAZNLLBEAWegeVsJdcMEGxPmTbl_9yiCFEqD9P6vvH_YNcYj10q-6GKeQ9OShCqRZCam0bGggdADMJAB1YohW44O1RlHErnK2KIcSTC4j6-GR4EJtJtWYoLvXPhxL265i98_QcmD_Gdon6PJCyhCZr=w679-h829-no?authuser=0" ,
        calorie: 864, 
        category: "burgers",
        price: 130,
        slug: "brienne-of-tarth",
        notice: "",
        ingredients: "Beef bacon, American cheese, lettuce, tomato, red onion, pickle, ketchup and our Famous sauce.",
        countInStock: 15,
      },
      {
        // _id: "5",
        name: "John Snow",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEXT2M78NeC22Jkf3_yHQgx_Lk3rffybGRpetYCMu0wU6dGdFRASYBGM5xev180yCwYXw4E6DjqKayp48KE-ewi7VOaoptHTDO5sU-HyAwAYGrxkj8PYp5UVpRyraq8qn1ugWmfaKI28B7widLycrKq-=w679-h829-no?authuser=0",
        calorie: 864, 
        category: "burgers",
        price: 140,
        slug: "john-snow",
        notice: "Vegetarian",
        ingredients: "Classic! American cheese, lettuce ,tomato, red onion, pickle, ketchup and our Famous sauce",
        countInStock: 13,
      },
      {
        // _id: "6",
        name: "Joffrey Baratheon",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEXQKKy0ZZcXwN2BTXjGQa9lJmjz9Gx4hPmBd-vWfVcyRhG1Wx1CCji9YoxHuNcT95Z9aXZGAayuAXKumVMq1kUjSE9UyDnZ0Vfu1EptB345RmWVQt9irKIwcbGThiYgHHA8bqS1tefh9HrE4JdSb1Jf=w679-h829-no?authuser=0" ,
        calorie: 864,
        category: "burgers", 
        price: 150,
        slug: "joffrey-baratheon",
        notice: "Vegetarian",
        ingredients: "2/3lb patty stuffed with American cheese, topped with lettuce, tomato, red onion, pickle, ketchup, our Famous sauce.",
        countInStock: 7,
      },
      {
        // _id: "7",
        name: "Khal Drogo",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEUW4VEDhQtKt2myMsjRfrSdAbsEVhIIUOqSXzaJhadAyZrINxr_sTn66m0ES8gB2Ejxmkm91hzAYXfhj2NUKPW98HipPpId0ffP6EKgW3ZjNsfFJMQGo2nm7dteDpJNEg49NUzABHLnLe4pqe8WJ6az=w679-h829-no?authuser=0",
        calorie: 864, 
        category: "burgers",
        price: 160,
        slug: "khal-drogo",
        notice: "Spicy",
        ingredients: "Jalapeno, hot sauce, habanero cheese, lettuce, tomato, red onion, pickle, ketchup and our Famous sauce.",
        countInStock: 16,
      },
      {
        // _id: "8",
        name: "Beric Dondarrion",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEXnBQNJZ1sQDm4YdPTIuo3hfJUu3qbR637bDY-42bppYEFZI2C5QtPjvQZFtrNjLw87adb9kqPM346vwX9iiu5Udtg0NeXmz9mVQ7FqkPeBTTosrMRKnvDlS9NfL_nrLtv5GQEr9KbuEkmqAkd9Rgyh=w679-h829-no?authuser=0",
        calorie: 864, 
        category: "burgers",
        price: 170,
        slug: "beric-dondarrion",
        notice: "Pork",
        ingredients: "Becon, lettuce, tomato, red onion, pickle, ketchup and our Famous sauce",
        countInStock: 20,
      },
      { 
        // _id: "9",
        name: "Lady",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEVaAK_WL3V-pdit3FtRB8rSORLyGbkKz6sOYgBwG2_wOzpLVLEb1vtI0CsiEVrAlB-9b2oV_QaAE1dFnPtvdYQCVFGg4Gla6ji2bth_3zHaeHLpg_c9qP67fBoWF1gqGkl4OTPGVbrrhpUlnOIWh5ni=w679-h829-no?authuser=0",
        calorie: 300,
        category: "drinks", 
        price: 5,
        slug: "lady",
        notice: "Alcoholic",
        ingredients: "Gin, tonic water, 2 lime wheels.",
        countInStock: 16,
      },
      {
        // _id: "10",
        name: "Melisandre",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEVFgvaMPSRwWy7qtHMiWgKCR2XvtW2r8l0p1dlB0mF--lZ_UYMDqYkbqooRzun2mWHGv8KLuszx0kK5DafonvyqJuGXbSKnncfiB3TwGFQmPbuEuIdh9BZuGSiOFsd3kIGO-7SF9ivrK9ES_oPMZxH-=w679-h829-no?authuser=0",
        calorie: 300,
        category: "drinks", 
        price: 5,
        slug: "melisandre",
        notice: "Alcoholic",
        ingredients: "Bacardi superior, wray & nephew, teresa orange, pineapple juice, cranberry juice,lime juice, Zombie mix, Fire mix, garnish-half passionfruit and dry ice.",
        countInStock: 16,
      },
      {
        // _id: "11",
        name: "Summer",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEV5xVQr8X4hfKyMSoWhw7fVjJdqRbyBdsT6uOyWIWFC5VA7TIrdGbNEO9WyEQk7G8QQ50kS3kOCyrTvBCwXR7udtQsBCxpFMozGdhf1bK3G9f4yOdYHMZ5or5RTDgKWGm7NQWV23B5rPuGf810xJQf7=w679-h829-no?authuser=0",
        calorie: 300,
        category: "drinks", 
        price: 6,
        slug: "summer",
        notice: "Peanut",
        ingredients: "Peanut, butter, banana, milk and dry ice.",
        countInStock: 16,
      },
      {
        // _id: "12",
        name: "Nymeria",
        image: "https://lh3.googleusercontent.com/pw/AL9nZEWEXuJ3E8LjlVYvyertxN3erz1D1QHy1ecoe059qxeih7vY-ZspQCLRmCQLhizJpOL_aofvWNFO1IKDx8G5mCu2FenOnwe_dKvUQx2EVxpRKpJ5YzwfAMHbmA4HikdJxHcNgfh4N1_wWWzGDGDNypSe=w679-h829-no?authuser=0",
        calorie: 300,
        category: "drinks", 
        price: 6,
        slug: "nymeria",
        notice: "",
        ingredients: "Banana, kiwi, strawberry, milk and dry ice.",
        countInStock: 16,
      }
    ]
};

export default data;